# Basic settings
description:  사이버닥터(CyberDoctor)
baseurl: "/"
url: "https://cyber-doctor.github.io" 
twitter_username: 
github_username:  
include: ['_pages']

# Build settings
markdown:    kramdown
# highlighter: pygments
lsi:         false
excerpt_separator: "\n\n"
gems:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock

# pagination
gems: [jekyll-paginate]
paginate: 5
paginate_path: "/page:num/"

# Enable comments
comments: true

