## Settings
title: CyberDoctor
owner: "CyberDoctor"
# url: "akiritsu.github.io"
baseurl: ""
baseurl: "/Dr.Cyber"
permalink: /:title/
description: ""
markdown: kramdown
webrick:
  headers:
    Access-Control-Allow-Origin: "*"
## Global Variables
email: "dr.cybersecu@gmail.com"
github: "akiritsu/pRoJEct-NeGYa"
# path to: css/, fonts/, img/ and js/
assets_path: "/assets" # i.e. "/assets" 
statement: "All Rights Reserved"
# default max toc levels: 1 - 6 (h1 - h6)
toc_level: 3
# texts randomly displayed in background
bgtext: "αβγδεζηθικλμνξοπρστυφχψω∷∫∮∝∞∧∨∑∏∪∩∈∵∴⊥‖∠⌒⊙≌∽√1234567890"