title: CyberDoctor
description: "CyberDoctor"
author:
  name: "CyberDoctor"
  email: "dr.cybersecu@gmail.com"
  url: "https://Cyber-Doctor.github.io"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "CyberDoctor"
year : "2019"
